### ISSUE TITLE
Can you set source language of files to English?

### ISSUE THREAD

**Issue by Blueberryy** [auronen/Gothic-1-localization#1]
Kinda want to help with russian translation of this project with some improvements but i cannot read german

**Comment by auronen** [comment]
Hello, thank you for your interest. I will add a contributing information to the readme.

The actual translations happen on my instance of [weblate](https://weblate.cokoliv.eu/) and there you can show any language to assist you with translations.  
If you have a discord, you can join us on our server, where we discuss and handle all of the things around these translations and corrections. Please join us here [GMC discord server](https://discord.gg/7zjNpVN8H6) and I will explain everything :)
